package com.azamovhudstc.scarpingtutorial.anibla.detail

data class Data(
    val __v: Int,
    val _id: String,
    val category: List<Category>,
    val country: String,
    val createdAt: String,
    val date: String,
    val description: Description,
    val image: String,
    val janr: List<Janr>,
    val length: String,
    val name: Name,
    val num: String,
    val price: String,
    val rating: Int,
    val rejissor: String,
    val screens: Screens,
    val slug: String,
    val status: Boolean,
    val studia: String,
    val tags: List<String>,
    val tarjimon: List<Tarjimon>,
    val tayming: List<Any>,
    val tip: String,
    val translator: List<Translator>,
    val type: Int,
    val updatedAt: String,
    val url: String,
    val video: String,
    val view: Int,
    val year: String
)